services:
  # Наш единственный локальный сервис: Бэкенд на Go
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: flashcards_go_api
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env   # <- ВСЕ пароли и ссылки лежат ТОЛЬКО там
    restart: unless-stopped